name: chatbook
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  any_link_preview: ^2.0.9
  audio_service: ^0.18.7
  audio_video_progress_bar: ^0.10.0
  audioplayers: ^1.0.1
  bubble: ^1.2.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_parsed_text: ^2.2.1
  flutter_svg: ^1.1.3
  get_it: ^7.2.0
  giphy_get: ^3.1.0
  google_fonts: ^3.0.1
  holding_gesture: ^1.1.0
  intl: ^0.17.0
  json_serializable: ^6.3.1
  just_audio: ^0.9.28
  just_audio_background: ^0.0.1-beta.7
  permission_handler: ^10.0.0
  record: ^4.4.0
  scrollable_positioned_list: ^0.3.2
  swipe_to_action: ^0.2.0
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
   assets:
     - assets/double_tick.svg
     - assets/pending_message.svg
     - assets/single_tick.svg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
